// Code generated by protoc-gen-go.
// source: consensus.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	consensus.proto

It has these top-level messages:
	Error
	Change
	Member
	Version
	GenericResponse
	PrepareRequest
	PrepareResponse
	AcceptRequest
	AddMemberRequest
	RemoveMemberRequest
	StartParticipation
	SubmitRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Error            *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Type             *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto1.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Error) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type Change struct {
	Change           []byte `protobuf:"bytes,1,opt,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Change) Reset()                    { *m = Change{} }
func (m *Change) String() string            { return proto1.CompactTextString(m) }
func (*Change) ProtoMessage()               {}
func (*Change) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Change) GetChange() []byte {
	if m != nil {
		return m.Change
	}
	return nil
}

type Member struct {
	Address          *string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto1.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Member) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

type Version struct {
	Instance         *uint64 `protobuf:"varint,1,req,name=instance" json:"instance,omitempty"`
	Sequence         *uint64 `protobuf:"varint,2,req,name=sequence" json:"sequence,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto1.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Version) GetInstance() uint64 {
	if m != nil && m.Instance != nil {
		return *m.Instance
	}
	return 0
}

func (m *Version) GetSequence() uint64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

type GenericResponse struct {
	Accepted         *bool  `protobuf:"varint,1,req,name=accepted" json:"accepted,omitempty"`
	Error            *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GenericResponse) Reset()                    { *m = GenericResponse{} }
func (m *GenericResponse) String() string            { return proto1.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()               {}
func (*GenericResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GenericResponse) GetAccepted() bool {
	if m != nil && m.Accepted != nil {
		return *m.Accepted
	}
	return false
}

func (m *GenericResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type PrepareRequest struct {
	Instance         *uint64 `protobuf:"varint,1,req,name=instance" json:"instance,omitempty"`
	Master           *Member `protobuf:"bytes,2,req,name=master" json:"master,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrepareRequest) Reset()                    { *m = PrepareRequest{} }
func (m *PrepareRequest) String() string            { return proto1.CompactTextString(m) }
func (*PrepareRequest) ProtoMessage()               {}
func (*PrepareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PrepareRequest) GetInstance() uint64 {
	if m != nil && m.Instance != nil {
		return *m.Instance
	}
	return 0
}

func (m *PrepareRequest) GetMaster() *Member {
	if m != nil {
		return m.Master
	}
	return nil
}

type PrepareResponse struct {
	Instance         *uint64 `protobuf:"varint,1,req,name=instance" json:"instance,omitempty"`
	Error            *Error  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrepareResponse) Reset()                    { *m = PrepareResponse{} }
func (m *PrepareResponse) String() string            { return proto1.CompactTextString(m) }
func (*PrepareResponse) ProtoMessage()               {}
func (*PrepareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PrepareResponse) GetInstance() uint64 {
	if m != nil && m.Instance != nil {
		return *m.Instance
	}
	return 0
}

func (m *PrepareResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AcceptRequest struct {
	Version          *Version  `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Changes          []*Change `protobuf:"bytes,2,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AcceptRequest) Reset()                    { *m = AcceptRequest{} }
func (m *AcceptRequest) String() string            { return proto1.CompactTextString(m) }
func (*AcceptRequest) ProtoMessage()               {}
func (*AcceptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AcceptRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *AcceptRequest) GetChanges() []*Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

type AddMemberRequest struct {
	Version          *Version `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Member           *Member  `protobuf:"bytes,2,req,name=member" json:"member,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AddMemberRequest) Reset()                    { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string            { return proto1.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()               {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AddMemberRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *AddMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	Version          *Version `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Member           *Member  `protobuf:"bytes,2,req,name=member" json:"member,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RemoveMemberRequest) Reset()                    { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string            { return proto1.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()               {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RemoveMemberRequest) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *RemoveMemberRequest) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type StartParticipation struct {
	Version          *Version  `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Cluster          *string   `protobuf:"bytes,2,req,name=cluster" json:"cluster,omitempty"`
	Self             *Member   `protobuf:"bytes,3,req,name=self" json:"self,omitempty"`
	Master           *Member   `protobuf:"bytes,4,req,name=master" json:"master,omitempty"`
	Members          []*Member `protobuf:"bytes,5,rep,name=members" json:"members,omitempty"`
	Snapshot         []byte    `protobuf:"bytes,6,req,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *StartParticipation) Reset()                    { *m = StartParticipation{} }
func (m *StartParticipation) String() string            { return proto1.CompactTextString(m) }
func (*StartParticipation) ProtoMessage()               {}
func (*StartParticipation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StartParticipation) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *StartParticipation) GetCluster() string {
	if m != nil && m.Cluster != nil {
		return *m.Cluster
	}
	return ""
}

func (m *StartParticipation) GetSelf() *Member {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *StartParticipation) GetMaster() *Member {
	if m != nil {
		return m.Master
	}
	return nil
}

func (m *StartParticipation) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *StartParticipation) GetSnapshot() []byte {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type SubmitRequest struct {
	Changes          []*Change `protobuf:"bytes,1,rep,name=changes" json:"changes,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SubmitRequest) Reset()                    { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string            { return proto1.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()               {}
func (*SubmitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SubmitRequest) GetChanges() []*Change {
	if m != nil {
		return m.Changes
	}
	return nil
}

func init() {
	proto1.RegisterType((*Error)(nil), "proto.Error")
	proto1.RegisterType((*Change)(nil), "proto.Change")
	proto1.RegisterType((*Member)(nil), "proto.Member")
	proto1.RegisterType((*Version)(nil), "proto.Version")
	proto1.RegisterType((*GenericResponse)(nil), "proto.GenericResponse")
	proto1.RegisterType((*PrepareRequest)(nil), "proto.PrepareRequest")
	proto1.RegisterType((*PrepareResponse)(nil), "proto.PrepareResponse")
	proto1.RegisterType((*AcceptRequest)(nil), "proto.AcceptRequest")
	proto1.RegisterType((*AddMemberRequest)(nil), "proto.AddMemberRequest")
	proto1.RegisterType((*RemoveMemberRequest)(nil), "proto.RemoveMemberRequest")
	proto1.RegisterType((*StartParticipation)(nil), "proto.StartParticipation")
	proto1.RegisterType((*SubmitRequest)(nil), "proto.SubmitRequest")
}

func init() { proto1.RegisterFile("consensus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x92, 0xcd, 0x6e, 0xe2, 0x30,
	0x10, 0xc7, 0x15, 0xc8, 0x07, 0x0c, 0x09, 0x20, 0xef, 0x25, 0xab, 0xd5, 0x7e, 0xc8, 0xda, 0x03,
	0x97, 0x65, 0x25, 0x9e, 0x60, 0xd1, 0xaa, 0xea, 0xa9, 0x12, 0x0a, 0x6a, 0xef, 0xc6, 0x99, 0x96,
	0x48, 0xc4, 0x49, 0x6d, 0x07, 0xa9, 0xef, 0xd5, 0x07, 0x6c, 0x6c, 0x03, 0xa5, 0x55, 0xd4, 0xf6,
	0xd0, 0x03, 0xc2, 0x19, 0xcf, 0xfc, 0xe7, 0x37, 0xff, 0x31, 0x4c, 0x78, 0x25, 0x14, 0x0a, 0xd5,
	0xa8, 0x79, 0x2d, 0x2b, 0x5d, 0x91, 0xc0, 0xfe, 0xd1, 0xdf, 0x10, 0x5c, 0x48, 0x59, 0x49, 0x92,
	0x40, 0x80, 0xe6, 0x90, 0x7a, 0xbf, 0xbc, 0xd9, 0x90, 0xc4, 0xe0, 0xeb, 0x87, 0x1a, 0xd3, 0x9e,
	0xf9, 0xa2, 0x29, 0x84, 0xff, 0xb7, 0x4c, 0xdc, 0x21, 0x19, 0x43, 0xc8, 0xed, 0xc9, 0xe6, 0xc5,
	0xf4, 0x2b, 0x84, 0x57, 0x58, 0x6e, 0x50, 0x92, 0x09, 0x44, 0x2c, 0xcf, 0x25, 0x2a, 0xe5, 0x24,
	0xe8, 0x1f, 0x88, 0x6e, 0x50, 0xaa, 0xa2, 0x12, 0x64, 0x0a, 0x83, 0x42, 0x28, 0xcd, 0x04, 0x37,
	0x75, 0xbd, 0x99, 0x6f, 0x22, 0x0a, 0xef, 0x1b, 0x34, 0x91, 0x9e, 0x89, 0xd0, 0x7f, 0x30, 0xb9,
	0x44, 0x81, 0xb2, 0xe0, 0x19, 0xaa, 0xda, 0xd0, 0x9a, 0x24, 0xc6, 0x39, 0xd6, 0x1a, 0x73, 0x5b,
	0x36, 0x20, 0xdf, 0x8e, 0x94, 0x86, 0x6b, 0xb4, 0x88, 0xdd, 0x30, 0x73, 0x3b, 0x02, 0x5d, 0xc2,
	0x78, 0x25, 0xb1, 0x66, 0x12, 0x33, 0x23, 0xad, 0x74, 0x47, 0xdf, 0xef, 0x10, 0x96, 0x4c, 0x69,
	0x94, 0xb6, 0xeb, 0x68, 0x91, 0x1c, 0x14, 0xdc, 0x10, 0x06, 0xe2, 0x24, 0xf1, 0x0c, 0xf1, 0x4a,
	0xe3, 0x4d, 0x88, 0x15, 0x24, 0x4b, 0xcb, 0x7c, 0x64, 0xf8, 0x09, 0xd1, 0xde, 0xd9, 0x60, 0xcb,
	0x47, 0x8b, 0xf1, 0x21, 0xff, 0x68, 0xce, 0x0f, 0x88, 0x9c, 0xa5, 0xaa, 0x15, 0xec, 0x9f, 0x31,
	0x39, 0xcb, 0x69, 0x06, 0xd3, 0x65, 0x9e, 0x3b, 0xc0, 0x0f, 0x8b, 0x9a, 0x39, 0x6d, 0x45, 0xf7,
	0x9c, 0xd7, 0xf0, 0x25, 0xc3, 0xb2, 0xda, 0xe3, 0xe7, 0xca, 0x3e, 0x7a, 0x40, 0xd6, 0x9a, 0x49,
	0xbd, 0x6a, 0x7f, 0x05, 0x2f, 0x6a, 0xa6, 0x4d, 0xd5, 0xbb, 0xb2, 0xed, 0xdb, 0xe1, 0xbb, 0xe6,
	0xb4, 0x96, 0x61, 0x6b, 0xb1, 0xaf, 0x70, 0x77, 0x9b, 0xf6, 0x3b, 0xba, 0x9c, 0xed, 0xd0, 0xef,
	0xba, 0x6e, 0xfd, 0x74, 0x8c, 0x2a, 0x0d, 0x5e, 0xf8, 0x79, 0xb8, 0x37, 0x4f, 0x4f, 0xb0, 0x5a,
	0x6d, 0x2b, 0x9d, 0x86, 0xad, 0x40, 0x4c, 0xff, 0x42, 0xb2, 0x6e, 0x36, 0x65, 0x71, 0xda, 0xd9,
	0xd9, 0x4a, 0xbc, 0x8e, 0x95, 0x3c, 0x05, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x7d, 0x23, 0xac, 0x4e,
	0x03, 0x00, 0x00,
}
